### ISSUE TITLE
Not building with node v6.9.1

### ISSUE THREAD

**Issue by balusamy** [anton-kotenko/kyotocabinet-node#8]
Getting the following errors:

../node_modules/nan/nan.h:602:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:602:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:603:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:608:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:608:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:613:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:613:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:614:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:619:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:619:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^

**Comment by anton-kotenko** [comment]
Hi. I'll try to fix the problem at the weekend.

**Comment by balusamy** [comment]
Hi, Any update on this issue?

**Comment by anton-kotenko** [comment]
Hi.
Sorry, had no time to fix problem.
Looked into sources, and it seems, that v8 and or nan library changed interfaced significantly enough to break everything.
I'll try fix it to the next week.

**Comment by anton-kotenko** [comment]
Fixed in pull request.
Add support for nodejs-6.9.1 and nodejs-7.4
https://github.com/anton-kotenko/kyotocabinet-node/pull/9

**Comment by anton-kotenko** [comment]
So, please check if everything is ok, and  close the issue.

**Comment by balusamy** [comment]
Tested with v6.9.1 and v7.4.0 and it works.   Thanks for your help.
